### ISSUE TITLE
Adjust css to account for apparent minor css changes in WP core

### ISSUE THREAD

**Issue by ramiabraham** [AffiliateWP/AffiliateWP#1558]
Our our about page, `wp-admin/index.php?page=affwp-getting-started` has some wonky text:

![wonk](http://i.imgur.com/eUOj5nK.png "wonk")

The apparent changes in WP core >= 4.6, in `wp-admin/css/about.css` are:

```css
.about-wrap .feature-section p {
	margin-left: auto;
	margin-right: auto;
}
```

The below style will correct for this:
```css
.dashboard_page_affwp-getting-started .about-wrap .feature-section p {
	margin-left: 0;
}
```

**Comment by michaelbeil** [comment]
Well, I guess that CSS change in core will work for some, but not or us.

**Comment by sumobi** [comment]
If we're going to correct it we'll need one more rule for the `What's New` tab:

```css
.dashboard_page_affwp-what-is-new .about-wrap .feature-section p,
.dashboard_page_affwp-getting-started .about-wrap .feature-section p {
    margin-left: 0;
}
```

We'll also need another rule for the `h2`'s on the `What's New` tab:

```css
.dashboard_page_affwp-what-is-new .about-wrap .feature-section h2 {
    text-align: left;
}

```

And we could probably simply the CSS a little so the final CSS would be:

```css
.dashboard_page_affwp-what-is-new .about-wrap p,
.dashboard_page_affwp-getting-started .about-wrap p {
	  margin-left: 0;
}

.dashboard_page_affwp-what-is-new .about-wrap h2 {
	text-align: left;
}
```

It would be super cool to use a similar layout to 4.6's welcome screen layout:

![screen shot 2016-08-24 at 4 46 47 pm](https://cloud.githubusercontent.com/assets/52581/17918655/1e42e718-6a1b-11e6-87dd-d385b94deb92.png)

![screen shot 2016-08-24 at 4 46 52 pm](https://cloud.githubusercontent.com/assets/52581/17918657/1e44bfd4-6a1b-11e6-9fd6-b63a385f6398.png)
![screen shot 2016-08-24 at 4 46 59 pm](https://cloud.githubusercontent.com/assets/52581/17918656/1e4468fe-6a1b-11e6-8533-5229daced75b.png)




There's also another approach and that is building new tabs for v1.9 based on 4.6's CSS. The reason our text is centered is because of the `feature-section` div, we shouldn't actually wrap that around everything like we've done but rather use it for each feature.
